Movie Rater/first/best/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views

app_name = 'best'

urlpatterns = [
    path("movies", views.MovieList.as_view(), name='movielist'),
    path("movie/<int:pk>", views.MovieDetail.as_view(), name='moviedetail'),
    path('person/<int:pk>', views.PersonDetail.as_view(template_name='person_detail.html'),\
     name='persondetail'),
    path('movies/top', views.TopMovies.as_view(), name='topmovies'),
    path("movie/<int:movie_id>/vote", views.CreateVote.as_view(), name='createvote'),
    path("movie/<int:movie_id>/vote/<int:pk>", views.UpdateVote.as_view(), name='updatevote'),
    path('movie/<int:movie_id>/image/upload', views.MovieImageUpload.as_view(), name='movie-image-upload'),
    
]

Movie Rater/first/first/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

MEDIA_FILE_PATHS = static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('best.urls', namespace='best')),
    path('user/', include('user.urls', namespace='user')),
    path('user/', include('django.contrib.auth.urls')),
] + MEDIA_FILE_PATHS

Movie Rater/first/user/urls.py
from django.urls import path
from .views import SignUpView

app_name = 'user'

urlpatterns = [
path('signup/', SignUpView.as_view(), name='signup'),
]

Movie Rater/first/best/models.py
from uuid import uuid4

from django.db import models
# from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.aggregates import (
    Sum
)
# Create your models here.


class VoteManager(models.Manager):
    def get_vote_or_unsaved_blank_vote(self, movie, user):
        try:
            return Vote.objects.get(
                movie=movie,
                user=user)
        except Vote.DoesNotExist:
            return Vote(
                movie=movie,
                user=user)


class MovieManger(models.Manager):
    def all_with_prefetch_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related('director')
        qs = qs.prefetch_related(
            'writers', 'actors')
        return qs

    def all_with_related_persons_and_score(self):
        qs = self.all_with_prefetch_persons()
        qs = qs.annotate(score=Sum('vote__value'))
        return qs

    def top_movies(self, limit=10):
        qs = self.get_queryset()
        qs = qs.annotate(
            vote_sum=Sum('vote__value'))
        qs = qs.exclude(
            vote_sum=None)
        qs = qs.order_by('-vote_sum')
        qs = qs[:limit]
        return qs


class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related(
            'directed',
            'writing_credits',
            'role_set__movie'
        )


class Person(models.Model):
    first_name = models.CharField(max_length=140, default='')
    last_name = models.CharField(max_length=140, default='')
    born = models.DateField()
    died = models.DateField(null=True, blank=True)
    objects = PersonManager()

    class Meta:
        ordering = ('last_name', "first_name")

    def __str__(self):
        if self.died:
            return '{}, {} ({}-{})'.format(self.last_name, self.first_name, self.born, self.died)
        return '{}, {} ({})'.format(self.last_name, self.first_name, self.born)



def cover_directory_path_with_uuid(
        instance, filename):
    return 'covers/{}/{}.{}'.format(
        instance.year,
        uuid4(),
        filename.split('.')[-1]
    )


class Movie(models.Model):
    RATINGS = (
            (0, 'NR - Not Rated'),
            (1, 'G - General Audiences'),
            (2, 'PG - Parental Guidence Suggested'),
            (3, 'R - Restricted'))

    title = models.CharField(max_length=140, default='Not Available')
    plot = models.TextField(default='-Not Available-')
    year = models.PositiveIntegerField(default=0000)
    rating = models.IntegerField(
        choices=RATINGS,
        default=0
    )
    runtime = models.PositiveIntegerField(default=0)
    website = models.URLField(blank=True)
    director = models.ForeignKey(Person, on_delete=models.SET_NULL, related_name='directed', null=True, blank=True)
    writers = models.ManyToManyField(Person, related_name='writing_credits', blank=True)
    actors = models.ManyToManyField(Person, related_name='acting_credits', blank=True)
    cover = models.ImageField(upload_to=cover_directory_path_with_uuid, blank=True)

    objects = MovieManger()

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return '{} ({})'.format(self.title, self.year)


class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    def __str__(self):
        return '{} {} {}'.format(self.movie_id, self.person_id, self.name)

    class Meta:
        unique_together = (
            'movie',
            'person',
            'name'
        )


class Vote(models.Model):
    UP = 1
    DOWN = -1
    CHOICES = (
        (UP, '👍'),
        (DOWN, '👎'))

    objects = VoteManager()       

    def get_vote_or_unsaved_blank_vote(self, movie, user):
        try:
            return Vote.objects.get(movie=movie, user=user)
        except Vote.DoesNotExist:
            return Vote(movie=movie, user=user)

    value = models.SmallIntegerField(choices=CHOICES, )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now=True)

    class Meta():
        unique_together = ('user', 'movie')

def movie_directory_path_with_uuid(
        instance, filename):
    return '{}/{}.{}'.format(
        instance.movie_id,
        uuid4(),
        filename.split('.')[-1]
    )


class MovieImage(models.Model):
    image = models.ImageField(
        upload_to=movie_directory_path_with_uuid)
    uploaded = models.DateTimeField(
        auto_now_add=True)
    movie = models.ForeignKey(
        'Movie', on_delete=models.CASCADE)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE)

Movie Rater/first/best/forms.py
from django import forms
from django.contrib.auth import get_user_model
from best.models import Vote, Movie, MovieImage


class VoteForm(forms.ModelForm):
    user = forms.ModelChoiceField(widget=forms.HiddenInput,
                                  queryset=get_user_model().objects.all(),
                                  disabled=True)
    movie = forms.ModelChoiceField(widget=forms.HiddenInput,
                                   queryset=Movie.objects.all(),
                                   disabled=True)

    value = forms.ChoiceField(widget=forms.RadioSelect, choices=Vote.CHOICES)  # lable='Vote',

    class Meta():
        model = Vote
        fields = ('value', 'user', 'movie')

class MovieImageForm(forms.ModelForm):

    movie = forms.ModelChoiceField(widget=forms.HiddenInput,
                                  queryset=Movie.objects.all(),
                                  disabled=True)
    user = forms.ModelChoiceField(widget=forms.HiddenInput,
                                queryset=get_user_model().objects.all(),
                                disabled=True)

    class Meta:
        model = MovieImage
        fields = ('image', 'user', 'movie')

Movie Rater/first/best/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect
from django.urls import reverse
from django.core.cache import cache
from .models import Movie, Person, Vote, MovieImage
from .forms import VoteForm, MovieImageForm
from best.mixins import CachePageVaryOnCookieMixin
# Create your views here.


class MovieList(CachePageVaryOnCookieMixin, ListView):
    model = Movie
    template_name = 'movielist.html'
    paginate_by = 3

    def get_context_data(self,
                         **kwargs):
        ctx = super(MovieList,
                    self).get_context_data(
            **kwargs)
        page = ctx['page_obj']
        paginator = ctx['paginator']
        ctx['page_is_first'] = (
            page.number == 1)
        ctx['page_is_last'] = (
            page.number == paginator.num_pages)
        return ctx


class MovieDetail(DetailView):
    model = Movie
    template_name = 'movie_detail.html'
    queryset = (Movie.objects.all_with_related_persons_and_score())

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['image_form'] = self.movie_image_form()
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(movie=self.object,
                                                               user=self.request.user)
            if vote.id:
                vote_form_url = reverse('best:updatevote',
                                        kwargs={
                                            'movie_id': vote.movie.id,
                                            'pk': vote.id
                                        })
            else:
                vote_form_url = (reverse('best:createvote',
                                         kwargs={
                                             'movie_id': vote.movie.id,
                                         }))
            vote_form = VoteForm(instance=vote)
            ctx['vote_form'] = vote_form
            ctx['vote_form_url'] = vote_form_url
        return ctx


    def movie_image_form(self):
        if self.request.user.is_authenticated:
            image_form = MovieImageForm()
            return image_form
        return None


class PersonDetail(DetailView):
    queryset = Person.objects.all_with_prefetch_movies()


class CreateVote(LoginRequiredMixin, CreateView):

    form_class = VoteForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse('best:moviedetail', kwargs={'pk': movie_id})

    def render_to_respond(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse('best:moviedetail', kwargs={'pk': movie_id})
        return redirect(to=movie_detail_url)


class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(queryset)
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied("Cannot change other user's vote")
        return vote

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse('best:moviedetail', kwargs={'pk': movie_id})

    def render_to_respond(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse('best:moviedetail', kwargs={'pk': movie_id})
        return redirect(to=movie_detail_url)


class MovieImageUpload(LoginRequiredMixin, CreateView):
    form_class = MovieImageForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def render_to_response(self, context, **response_kwargs):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse(
            'best:moviedetail',
            kwargs={'pk': movie_id})
        return redirect(
            to=movie_detail_url)

    def get_success_url(self):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse(
            'best:moviedetail',
            kwargs={'pk': movie_id})
        return movie_detail_url

class TopMovies(ListView):
    template_name = 'top_movies_list.html'
    queryset = Movie.objects.top_movies(limit=3)
    def get_queryset(self):
        limit = 10
        key = 'top_movies_%s' % limit
        cached_qs = cache.get(key)
        if cached_qs:
            same_django = cached_qs._django_version == django.get_version()
            if same_django:
                return cached_qs
        qs = Movie.objects.top_movies(
            limit=limit)
        cache.set(key, qs)
        return qs

Movie Rater/first/best/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>
        {% block title %}MoviesBoom{% endblock %}
  </title>

  <!-- Bootstrap core CSS -->
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Bangers&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Bebas+Neue&display=swap" rel="stylesheet">
  <!-- <link href="{% static 'css/shop-item.css' %}" rel="stylesheet"> -->
  <!-- <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet"> -->
</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-default" style="background-color:#cccccc;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" >
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'best:movielist' %}">MoviesBoom
        <span><img alt="Brand" src="{% static 'images/logo.png'%}" style="margin-left: 5px"></span>
      </a>

    </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'best:movielist' %}">Home<span class="sr-only">(current)</span></a></li>
        <li><a href="{% url 'best:topmovies' %}">Top 10</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        <li><a href="{% url 'login' %}">Login</a></li>
        {% endif %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h1 style="font-family: 'Bebas Neue', cursive; font-size: 50px;color:#ff9900;">MoviesBoom<img style="display: inline;margin-left: 5px;" src="{% static 'images/logo.png' %}"></h1>
        <p style="color: #262626; display: inline;">A Django and Bootstrap powered movie rater</p>
            </div>
  </div>
        <!-- <ul class="list-unstyled"> -->
        <div class="container" style="padding-top: 20px;">
                <!-- <div class="col-sm-8 mymdb.main"> -->
                    {% block main %}{% endblock %}
                    <div class="col-sm-3 offset-sm-1">
                    {% block sidebar %}{% endblock %}
                    </div>
            </div>
          </div>
      <!-- </disv> -->
<!-- Footer -->
  <footer style="position: fixed;bottom:0;padding-top:1rem;padding-bottom: 1em;background-color:#cccccc;width: 100%;">
    <div class="container">
      <p class="m-0 text-center text-white" style="color:#000;text-align:center;-ms-flex-order:0;order:0;">Copyright &copy; MoviesBoom 2019</p>
    </div>
  </footer>
    <!-- /.container -->

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'js/jquery.slim.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>

Movie Rater/first/best/templates/movie_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{object.title}} - {{ block.super }}
{% endblock title %}

{% block main %}
  <!-- Page Content -->
  <div class="container">
      <!-- /.col-lg-3 -->
      <div class="row">

      <div class="col-lg-9">

        <div class="panel panel-warning">
            <h3 class="panel-heading">{{object}}</h3>
            <img style="max-width:100%;height:auto;width:100%;border-top-left-radius:calc(.25rem - 1px);border-top-right-radius:calc(.25rem - 1px)" 
            src="{{object.cover.url}}" alt="Brand">
            <div class="panel-body">
            <!-- <h4>$24.99</h4> -->
            <p class="panel-body" style="font-size: 17px;">{{object.plot}}</p>
            <p class="panel-heading" style="font-size: 17px;"><b>BoomScore:</b> {{object.score|default_if_none:"TBD"}}</p>
          </div>
          <p class="panel-body">Images Uploaded by Users:</p>
          <ul class="movie-image list-inline">
            {% for i in object.movieimage_set.all %}
              <li class="list-inline-item">
                <img src="{{ i.image.url }}">
              </li>
            {% endfor %}
              </ul>
        </div>
        <!-- /.card -->
        <div> 
          <div style="padding:.75rem 1.25rem;margin-bottom:0;background-color:rgba(0,0,0,.03);border-bottom:1px solid rgba(0,0,0,.125);">
            <b class="panel-heading">Crew/Cast</b>
          </div>
          <div class="panel-body" style="ms-flex:1 1 auto;flex:1 1 auto;">
            <!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
            <hr>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
            <hr>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
            <small class="text-muted">Posted by Anonymous on 3/1/17</small>
            <hr> -->
            <p>
        <b>Directed by:</b>{{object.director}}<br>
        <b>Actors:</b> {% for area in object.actors.all %}{{ area }}<br/>{% endfor %}
        <b>Writers:</b> {% for area in object.writers.all %}{{ area }}<br/>{% endfor %}
          </p>
          <p>{{object.random}}</p>
            <hr>
            <!-- <a href="#" class="btn btn-success">Leave a Review</a> -->
          </div>
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col-lg-9 -->
  <!-- /.container -->
    {% endblock %}
  
{% block sidebar %}
<div class="panel panel-warning">
  <p class="panel-heading">This movie is Rated as</p>
  <div class="panel-body" style="font-size: 17px; ">
    <span class="label label-warning">
        {{ object.get_rating_display }}
    </span>
  </div>
{% if image_form %}
<div class="panel panel-warning">
  <p class="panel-heading">Upload Movie Images</p>
  <div class="panel-body">
  <form method="POST"
        enctype="multipart/form-data"
          action="{% url 'best:movie-image-upload' movie_id=object.id %}">
          {% csrf_token %}
          {% for i in image_form %}
          {{i}}
          {% endfor %}
          <p>
            <button class="btn btn-warning" style="margin-top: 10px;">
              Upload
            </button>
          </p>
        </form>
      </div>
      </div>
{% endif %}
<div class="panel panel-warning">
<p class="panel-heading">Vote</p>
<div class="panel-body">
    {% if vote_form %}
    <form method="POST" action="{{vote_form_url}}" >
        {% csrf_token %}
        {% for i in vote_form %}
        {{i}}
        {% endfor %}
        <button class="btn btn-warning">Vote</button>
    </form>
    {% else %}
    <p>Log in to vote for this movie</p>
    {% endif %}
</div>
</div>
</div>
</div>
</div>
    {% endblock %}

Movie Rater/first/best/templates/movielist.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    All Movies
{% endblock title %}

{% block main %}
<ul>    
{% for movie in object_list %}
    <li>
        <a class="list-group" href="{% url 'best:moviedetail' pk=movie.id %}" style="font-family: 'Bangers', cursive;font-size: 30px;">
        {{movie}}
    </a>
    </li>
{% endfor %}
</ul>
{% if is_paginated %}
<nav>
    <ul class="pagination">
        <li class="page-item">
            <a 
            href="{% url 'best:movielist' %}"
            class="page-link">
        First</a>
        </li>
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a 
            href="{% url 'best:movielist' %}?page={{page_obj.previous_page_number}}"
            class="page-link">
            {{page_obj.previous_page_number}}
        </a>
        </li>    
        {% endif %}
            <!-- <li class="page-item active">
                <a
                href="{% url 'best:movielist' %}?page={{page_obj.number}}"
                class="page-link">
                {{page_obj.number}}
            </a>
            </li> -->
            
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a 
                    href="{% url 'best:movielist' %}?page={{page_obj.next_page_number}}"
                    class="page-link">
                {{page_obj.next_page_number}}</a>
                </li>
            {% endif %}
            <li class="page-item">
                <a 
                href="{% url 'best:movielist' %}?page=6"
                class="page-link">
            Last</a>
            </li>
    </ul>
</nav>
{% endif %}
    
{% endblock %}

Movie Rater/first/best/templates/person_detail.html
{% extends 'base.html' %}


{% block title %}
    {{object.first_name}}
    {{object.last_name}}
{% endblock title %}
    

{% block main %}
    <h1>{{object}}</h1>
    <h2>Actor</h2>
    <ul>
        
        {% for role in object.role_set.all %}
            <li>
                <a href="{% url 'best:moviedetail' role.movie.id %}">
                    {{role.movie}}
                </a>:
                {{role.name}}
            </li>
        {% endfor %}
    </ul>
    <h2>Writer</h2>
    <ul>
        
        {% for movie in object.writing_credits.all %}
            <li>
                <a href="{% url 'best:moviedetail' movie.id %}">
                    {{movie}}
                </a>
            </li>
        {% endfor %}
    </ul>
    <h2>Director</h2>
    <ul>
        
        {% for movie in object.directed.all %}
        <li>
            <a href="{% url 'best:moviedetail' movie.id %}">
                {{movie}}
            </a>
        </li>
        {% endfor %}
    </ul>
{% endblock main %}

{block sidebar}
{# rating div omitted #}
<div>
    {% if vote_form %}
    <form method="POST" action="{{vote_form_url}}" >
        {% csrf_token %}
        {{vote_form.as_p}}
        <button class="btn btn-primary">Vote</button>
    </form>
    {% else %}
    <p>Log in to vote for this movie</p>
    {% endif %}
</div>
{ endblock sidebar}

Movie Rater/first/best/templates/top_list.html
{% extends 'base.html' %}
{% load cache %}

{% block title %}
Top 10 Movies (Cached)
{% endblock %}

{% block main %}
<h1>
	Top 10 Movies
</h1>
{% cache 300 top10 %}
<ol>
	{% for movie in object_list %}
		<li>
			<a href="{% url 'best:moviedetail' pk=movie.id %}">
				{{movie}}
			</a>
		</li>
	{% endfor %}
</ol>
{% end cache %}
{% endblock %}

Movie Rater/first/best/templates/top_movies_list.html
{% extends 'base.html' %}

{% block title %}
Top 10 Movies
{% endblock title %}

{% block main %}
<h1>Top 10 Movies</h1>
<ol>
	{% for i in object_list %}
	<li>
		<a href="{% url 'best:moviedetail' pk=i.id %}">
			{{i}}
		</a>
	</li>
	{% endfor %}
</ol>
{% endblock %}